config/routes.rb
Kpnavi::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :checkup_entries
end

app/models/checkup_entry.rb
class CheckupEntry < ActiveRecord::Base
  # TODO: ERをいれいる
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable,
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/checkup_entries_controller.rb
class CheckupEntriesController < ApplicationController
  before_action :set_checkup_entry, only: [:show, :edit, :update, :destroy]

  # GET /checkup_entries
  # GET /checkup_entries.json
  def index
    @checkup_entries = CheckupEntry.all
  end

  # GET /checkup_entries/1
  # GET /checkup_entries/1.json
  def show
  end

  # GET /checkup_entries/new
  def new
    @checkup_entry = CheckupEntry.new
  end

  # GET /checkup_entries/1/edit
  def edit
  end

  # POST /checkup_entries
  # POST /checkup_entries.json
  def create
    @checkup_entry = CheckupEntry.new(checkup_entry_params)

    respond_to do |format|
      if @checkup_entry.save
        format.html { redirect_to @checkup_entry, notice: 'Checkup entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @checkup_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @checkup_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkup_entries/1
  # PATCH/PUT /checkup_entries/1.json
  def update
    respond_to do |format|
      if @checkup_entry.update(checkup_entry_params)
        format.html { redirect_to @checkup_entry, notice: 'Checkup entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @checkup_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkup_entries/1
  # DELETE /checkup_entries/1.json
  def destroy
    @checkup_entry.destroy
    respond_to do |format|
      format.html { redirect_to checkup_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkup_entry
      @checkup_entry = CheckupEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkup_entry_params
      params.require(:checkup_entry).permit(:entry_no, :staus, :request_datetime_1, :request_datetime_2, :request_datetime_3, :cource_code, :request_type, :request_prefecture_code, :request_hospital, :exam_datetime, :exam_hospital, :exam_note)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    # TODO
    # cource select, client select.
    #
    # コントローラ名とモデル名は一致する設計が望ましい＝リソース（原則）

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 他人の情報を編集できるのは、実践的にはない＝
  # この辺は、限定可操作を実装する
  # role = cancan で？ user/3=admin? #>false
  # TODO: current_user プロファイル表示系に変更してみる

  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def index
    # TODO all.order 指定
    @users = User.all
  end

  def show
  end

  # GET /users/1/edit
  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        # TODO: custume i18n_field(:updated)
        format.html { redirect_to @user, notice: 'success updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :kana, :sex, :birth_of_date, :insurance_no, :zipcode, :prefecture_code, :address, :tel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/checkup_entries_helper.rb
module CheckupEntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/checkup_entries/_form.html.haml
= simple_form_for(@checkup_entry) do |f|
  = f.error_notification

  .form-inputs
    = f.input :entry_no
    = f.input :staus
    = f.input :request_datetime_1
    = f.input :request_datetime_2
    = f.input :request_datetime_3
    = f.input :cource_code
    = f.input :request_type
    = f.input :request_prefecture_code
    = f.input :request_hospital
    = f.input :exam_datetime
    = f.input :exam_hospital
    = f.input :exam_note

  .form-actions
    = f.button :submit

app/views/checkup_entries/edit.html.haml
%h1 Editing checkup_entry

= render 'form'

= link_to 'Show', @checkup_entry
\|
= link_to 'Back', checkup_entries_path

app/views/checkup_entries/index.html.haml
%h1 Listing checkup_entries

%table.table.table-bordered.table-striped
  %tr
    %th Entry no
    %th Staus
    %th Request datetime 1
    %th Request datetime 2
    %th Request datetime 3
    %th Cource code
    %th Request type
    %th Request prefecture code
    %th Request hospital
    %th Exam datetime
    %th Exam hospital
    %th Exam note
    %th
    %th
    %th

  - @checkup_entries.each do |checkup_entry|
    %tr
      %td= checkup_entry.entry_no
      %td= checkup_entry.staus
      %td= checkup_entry.request_datetime_1
      %td= checkup_entry.request_datetime_2
      %td= checkup_entry.request_datetime_3
      %td= checkup_entry.cource_code
      %td= checkup_entry.request_type
      %td= checkup_entry.request_prefecture_code
      %td= checkup_entry.request_hospital
      %td= checkup_entry.exam_datetime
      %td= checkup_entry.exam_hospital
      %td= checkup_entry.exam_note
      %td= link_to 'Show', checkup_entry
      %td= link_to 'Edit', edit_checkup_entry_path(checkup_entry)
      %td= link_to 'Destroy', checkup_entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Checkup entry', new_checkup_entry_path

app/views/checkup_entries/new.html.haml
%h1 New checkup_entry

= render 'form'

= link_to 'Back', checkup_entries_path

app/views/checkup_entries/show.html.haml
%p#notice= notice

%p
  %b Entry no:
  = @checkup_entry.entry_no
%p
  %b Staus:
  = @checkup_entry.staus
%p
  %b Request datetime 1:
  = @checkup_entry.request_datetime_1
%p
  %b Request datetime 2:
  = @checkup_entry.request_datetime_2
%p
  %b Request datetime 3:
  = @checkup_entry.request_datetime_3
%p
  %b Cource code:
  = @checkup_entry.cource_code
%p
  %b Request type:
  = @checkup_entry.request_type
%p
  %b Request prefecture code:
  = @checkup_entry.request_prefecture_code
%p
  %b Request hospital:
  = @checkup_entry.request_hospital
%p
  %b Exam datetime:
  = @checkup_entry.exam_datetime
%p
  %b Exam hospital:
  = @checkup_entry.exam_hospital
%p
  %b Exam note:
  = @checkup_entry.exam_note

= link_to 'Edit', edit_checkup_entry_path(@checkup_entry)
\|
= link_to 'Back', checkup_entries_path

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
/ # add navigation links to this file
- if user_signed_in?
  %li= link_to 'Logout', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Login', new_user_session_path
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
- else
  %li= link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  %li= link_to 'Users', users_path
  %li= link_to 'Checkup Entries', checkup_entries_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Kpnavi'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Kpnavi'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/users/_form.html.haml
= simple_form_for(@user, :html => { :class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs.inputs
    = f.input :name
    = f.input :kana
    - # TODO: 年月のスライド固定化は後で問題になるかも
    - # ex. Date.today.ago(70.years).year
    = f.input :birth_of_date, :as => :date, :start_year => Date.today.year - 70, :end_year => Date.today.year - 16, :discard_day => false, :order => [:year, :month, :day], :input_html => { :class => "input-small" }
    = f.input :sex, :as => :select, include_blank: false
    = f.input :insurance_no
    = f.input :zipcode, :input_html => { :class => "input-mini" }
    = f.input :prefecture_code
    = f.input :address, :as => :text
    = f.input :tel

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/users/edit.html.haml
%h3 Editing User

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email if @user.email
%p
  %b Kana:
  = @user.kana
%p
  %b Birth of Date:
  = @user.birth_of_date
%p
  %b Sex:
  = @user.sex == 1 ? '男' : @user.sex == 2 ? '女' : '不明'
%p
  %b Insurance No:
  = @user.insurance_no
%p
  %b Prefecture:
  = @user.prefecture_code
%p
  %b address:
  = @user.address
%p
  %b Tel:
  = @user.tel

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path